export enum SERIALIZE_GROUP {
  GROUP_BASE = 'GROUP_BASE',
  GROUP_ALL_BASE = 'GROUP_ALL_BASE',

  GROUP_ADMIN = 'GROUP_ADMIN',
  GROUP_ALL_ADMIN = 'GROUP_ALL_ADMIN',
  GROUP_ADMIN_PROFILE = 'GROUP_ADMIN_PROFILE',

  GROUP_MEDIA_OBJECT = 'GROUP_MEDIA_OBJECT',
  GROUP_ALL_MEDIA_OBJECT = 'GROUP_ALL_MEDIA_OBJECT',

  GROUP_PERMISSION = 'GROUP_PERMISSION',
  GROUP_ALL_PERMISSION = 'GROUP_ALL_PERMISSION',

  GROUP_MENU = 'GROUP_MENU',
  GROUP_ALL_MENU = 'GROUP_ALL_MENU',

  GROUP_ALL_ROLE = 'GROUP_ALL_ROLE',
  GROUP_ROLE = 'GROUP_ROLE',

  GROUP_ALL_USER = 'GROUP_ALL_USER',
  GROUP_USER_PROFILE = 'GROUP_USER_PROFILE',
  GROUP_USER = 'GROUP_USER',
  GROUP_USER_FILTER = 'GROUP_USER_FILTER',
  GROUP_USER_FULL_NAME = 'GROUP_USER_FULL_NAME',
  GROUP_USER_TRANSACTION = 'GROUP_USER_TRANSACTION',

  GROUP_STUDENT_PROFILE = 'GROUP_STUDENT_PROFILE',
  GROUP_ALL_ASSESSMENT_COURSE = 'GROUP_ALL_ASSESSMENT_COURSE',
  GROUP_ALL_INSTRUCTOR = 'GROUP_ALL_INSTRUCTOR',
  GROUP_ANSWER_ASSESSMENT_COURSE = 'GROUP_ANSWER_ASSESSMENT_COURSE',
  GROUP_INSTRUCTOR_PROFILE = 'GROUP_INSTRUCTOR_PROFILE',
  GROUP_FACULTY = 'GROUP_FACULTY',
}
